const ffmpeg = require('fluent-ffmpeg');
const path = require('path');
const fs = require('fs');
const { EventEmitter } = require('events');
const config = require('./config');
const channelManager = require('./channelManager');

class StreamManager extends EventEmitter {
  constructor() {
    super();
    this.activeStreams = new Map();
    this.ensureOutputDir();
  }

  ensureOutputDir() {
    if (!fs.existsSync(config.paths.hlsOutput)) {
      fs.mkdirSync(config.paths.hlsOutput, { recursive: true });
    }
  }

  getChannelOutputDir(channelId) {
    const dir = path.join(config.paths.hlsOutput, channelId);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    return dir;
  }

  startStream(channelId, source) {
    if (this.activeStreams.has(channelId)) {
      this.stopStream(channelId);
    }

    const outputDir = this.getChannelOutputDir(channelId);
    const playlistPath = path.join(outputDir, 'stream.m3u8');

    const sourceConfig = this._resolveSource(source);

    const proc = ffmpeg(sourceConfig.input)
      .inputOptions(sourceConfig.inputOptions)
      .audioCodec('libopus')
      .audioBitrate(config.audio.bitrate)
      .audioFrequency(config.audio.sampleRate)
      .audioChannels(2)
      .outputOptions([
        '-f hls',
        `-hls_time ${config.audio.hlsSegmentDuration}`,
        `-hls_list_size ${config.audio.hlsListSize}`,
        '-hls_flags delete_segments+append_list+omit_endlist+independent_segments',
        '-hls_segment_type mpegts',
        `-hls_segment_filename ${path.join(outputDir, 'seg%05d.ts')}`,
        '-hls_allow_cache 0',
        '-movflags +faststart',
      ])
      .output(playlistPath)
      .on('start', (cmd) => {
        console.log(`[Stream ${channelId}] Started: ${cmd}`);
        channelManager.setActive(channelId, true);
        this.emit('stream:started', { channelId });
      })
      .on('error', (err) => {
        console.error(`[Stream ${channelId}] Error:`, err.message);
        this.activeStreams.delete(channelId);
        channelManager.setActive(channelId, false);
        this.emit('stream:error', { channelId, error: err.message });
      })
      .on('end', () => {
        console.log(`[Stream ${channelId}] Ended`);
        this.activeStreams.delete(channelId);
        channelManager.setActive(channelId, false);
        this.emit('stream:ended', { channelId });
      });

    proc.run();
    this.activeStreams.set(channelId, { proc, source, startedAt: new Date().toISOString() });

    return { channelId, playlistUrl: `/hls/${channelId}/stream.m3u8` };
  }

  stopStream(channelId) {
    const stream = this.activeStreams.get(channelId);
    if (!stream) return false;

    try {
      stream.proc.kill('SIGTERM');
    } catch (e) {
      console.warn(`[Stream ${channelId}] Kill error:`, e.message);
    }

    this.activeStreams.delete(channelId);
    channelManager.setActive(channelId, false);
    this._cleanupSegments(channelId);
    this.emit('stream:stopped', { channelId });
    return true;
  }

  restartStream(channelId) {
    const stream = this.activeStreams.get(channelId);
    if (!stream) return false;
    const { source } = stream;
    this.stopStream(channelId);
    setTimeout(() => this.startStream(channelId, source), 500);
    return true;
  }

  startTestTone(channelId, frequency = 440) {
    return this.startStream(channelId, {
      type: 'testtone',
      frequency,
    });
  }

  _resolveSource(source) {
    switch (source.type) {
      case 'alsa':
        return {
          input: `hw:${source.card || 0},${source.device || 0}`,
          inputOptions: ['-f alsa', `-ar ${config.audio.sampleRate}`, '-ac 2'],
        };
      case 'pulse':
        return {
          input: source.device || 'default',
          inputOptions: ['-f pulse', `-ar ${config.audio.sampleRate}`, '-ac 2'],
        };
      case 'aes67': {
        // AES67 multicast RTP: rtp://239.x.x.x:PORT
        // SDP file describing the stream (generated by Dante/AES67 console)
        const rtpUrl = source.sdpFile
          ? source.sdpFile   // path to .sdp file
          : `rtp://${source.multicastAddress}:${source.port || 5004}`;
        const inputOpts = [
          '-re',
          '-protocol_whitelist file,udp,rtp,crypto,data',
          `-buffer_size ${(config.audio.rtpBufferMs * config.audio.sampleRate * 4) / 1000}`,
        ];
        if (source.sdpFile) {
          inputOpts.unshift('-f sdp');
        } else {
          inputOpts.unshift('-f rtp');
        }
        if (config.audio.multicastInterface) {
          inputOpts.push(`-localaddr ${config.audio.multicastInterface}`);
        }
        return { input: rtpUrl, inputOptions: inputOpts };
      }
      case 'rtsp':
        return {
          input: source.url,
          inputOptions: ['-rtsp_transport tcp'],
        };
      case 'file':
        return {
          input: source.path,
          inputOptions: ['-stream_loop -1'],
        };
      case 'testtone':
        return {
          input: `sine=frequency=${source.frequency || 440}:duration=9999`,
          inputOptions: ['-f lavfi', `-ar ${config.audio.sampleRate}`],
        };
      case 'silence':
        return {
          input: 'anullsrc=r=48000:cl=stereo',
          inputOptions: ['-f lavfi'],
        };
      default:
        throw new Error(`Unknown source type: ${source.type}`);
    }
  }

  _cleanupSegments(channelId) {
    const outputDir = path.join(config.paths.hlsOutput, channelId);
    if (!fs.existsSync(outputDir)) return;
    try {
      const files = fs.readdirSync(outputDir);
      files.forEach(f => {
        if (f.endsWith('.ts') || f.endsWith('.m3u8')) {
          fs.unlinkSync(path.join(outputDir, f));
        }
      });
    } catch (e) {
      console.warn(`[Stream ${channelId}] Cleanup error:`, e.message);
    }
  }

  getActiveStreams() {
    const result = [];
    for (const [channelId, stream] of this.activeStreams) {
      result.push({ channelId, source: stream.source, startedAt: stream.startedAt });
    }
    return result;
  }

  isStreaming(channelId) {
    return this.activeStreams.has(channelId);
  }
}

module.exports = new StreamManager();
